import postgres, { PostgresError } from "postgres";
import { types } from "./exports";
import bcrypt from 'bcrypt'

const SALT_ROUNDS = 10;

const dbUrl = process.env.NODE_ENV === 'production' ? process.env.POSTGRES_PRODUCTION! : process.env.POSTGRES_TEST!

const sql = postgres(dbUrl,
    {
        ssl: process.env.NODE_ENV === 'production' ? 'require' : false,
    });
    export async function createUser(user: types.UserInsert): Promise<types.UserSafe | null> {

    const userExists = await findUserByName(user.name);
    if (userExists) {
        return null;
    }

    const hashedPassword = await bcrypt.hash(user.password, SALT_ROUNDS);

    try {
        const result = await sql<types.UserUnsafe[]>`
            INSERT INTO users 
                (name, password)
            VALUES (
                ${user.name}, ${hashedPassword} 
            )
            RETURNING user_id, name, created_at
        `;

        return result.length === 1 ? sanitizeUser(result[0]) : null;
    } catch (error) {
        console.error(error);
    }

    return null;
}

export async function findUserByName(name: string) {
    try {
        const result = await sql<types.UserUnsafe[]>`
            SELECT 
                user_id, name, password, created_at
            FROM users
            WHERE name=${name}
        `;
        return result.length === 1 ? result[0] : null;
    } catch (error) {
        console.error(error);
    }

    return null;
}

export async function findUserById(id: string) {
    try {
        const result = await sql<types.UserUnsafe[]>`
            SELECT
                user_id, name, password, created_at
            FROM users
            WHERE user_id=${id}
        `;
        return result.length === 1 ? result[0] : null;
    } catch (error) {
        console.error(error);
    }

    return null;
}


export async function deleteUserById(id: string) {
    try {
        await sql`
            DELETE FROM users WHERE user_id=${id}
        `;

    } catch (error) {
        console.error(error);
    }

    return null;
}

export async function updateUser(user: types.UserUnsafe) {
    if (!user.password) {
        return null;
    }

    const hashedPassword = await bcrypt.hash(user.password, SALT_ROUNDS);

    try {
        await sql`
            UPDATE users SET 
                name = ${user.name}, 
                password = ${hashedPassword}
            WHERE user_id=${user.user_id}
        `;
    } catch (error) {
        console.error(error);
    }

    return null;
}

export async function createToken(user_id: string, token: string, expires: string) {
    try {
        await sql`
            INSERT INTO secure_tokens (
                user_id, token, expires
            )
            VALUES (
                ${user_id}, ${token}, ${expires}
            )
        `
        return true;
    }
    catch (error) {
        console.error(error);
    }
    return false;
}

export async function findValidTokensByUserId(user_id: string): Promise<types.SecureToken[] | null> {
    try {
        await removeExpiredTokens();

        const response = await sql<types.SecureToken[]>`
            SELECT token_id, token, expires FROM secure_tokens
            WHERE user_id=${user_id}
        `;

        return response.length >= 1 ? response : null;
    } catch (error) {
        console.error(error);
    }
    return null;
}

export async function deleteTokenById(token_id: string) {
    try {
        await sql`DELETE FROM secure_tokens WHERE token_id=${token_id}`;
    } catch (error) {
        console.error(error);
    }
}

export async function createTables() {
    try {
        // Users
        await sql`
            CREATE TABLE IF NOT EXISTS users (
                user_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                name varchar(64) NOT NULL,
                password varchar(255) NOT NULL,
                created_at timestamp with time zone NOT NULL DEFAULT NOW()
            )

        `;
        // Tokens
        await sql`
            Create TABLE IF NOT EXISTS secure_tokens (
                token_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                token varchar(255),
                user_id bigint NOT NULL REFERENCES users,
                expires timestamp with time zone NOT NULL
            )
        `;
    } catch (error) {
        console.error(error);
    }
}

export async function deleteTables() {
    try {
        // Tokens
        await sql`
            DROP TABLE IF EXISTS secure_tokens, users
        `

    } catch (error) {
        console.error(error);
    }
}

export function sanitizeUser(user: types.UserUnsafe): types.UserSafe {
    const { password, created_at, ...userSafe } = user;
    return userSafe;
}

export async function removeExpiredTokens() {
    await sql`DELETE FROM secure_tokens WHERE expires <= NOW()`
}

export async function testTablesExist() {
    try {

        const res = await sql<types.TestTableExists[]>`
            SELECT COUNT(*) = 2 as exists
            FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name IN ('users', 'secure_tokens')`
        return res ? res[0].exists : false;
    } catch (error) {
        console.error(error);
    }
    return false;
}